window:
  opacity: 0.8
  decorations: buttonless
env:
  TERM: xterm-256color
font:
  normal:
    family: ProFont IIx Nerd Font Mono
    style: Regular
  bold:
    family: ProFont IIx Nerd Font Mono
    style: Bold
  italic:
    family: ProFont IIx Nerd Font Mono 
    style: Italic
  size: 11
key_bindings:
  - { key: J, mods: Alt, chars: "\x1bj" }
  - { key: K, mods: Alt, chars: "\x1bk" }
  - { key: H, mods: Alt, chars: "\x1bh" }
  - { key: L, mods: Alt, chars: "\x1bl" }
    
scrolling:
  history: 40000
